package org.brocco.enums;

public enum UnidadePrisional {
    
    ALVARO_CARVALHO_PENIT_I("Álvaro de Carvalho - Penit. I \"Valentim Alves da Silva\" + APP"),
    ALVARO_CARVALHO_PENIT_II("Álvaro de Carvalho - Penit. II"),
    BALBINOS_PENIT_I("Balbinos - Penit. I \"Rodrigo dos Santos Freitas\" + APP"),
    BALBINOS_PENIT_II("Balbinos - Penit. II \"Gilmar Monteiro de Souza\""),
    BAURU_CPP_I("Bauru - CPP I \"Dr. Alberto Brocchieri\""),
    BAURU_CPP_II("Bauru - CPP II \"Dr. Eduardo de Oliveira Vianna\""),
    CAIUA_PENIT("Caiuá - Penit. \"Bruno Luiz Airoldi Leite\""),
    CAIUA_CDP("Caiuá - CDP \"Tácio Aparecido Santana\" + PC"),
    HORTOLANDIA_PENIT_II("Hortolândia - Penit. II \"Odete Leite de Campos Critter\" RSA"),
    HORTOLANDIA_PENIT_III("Hortolândia - Penit. III"),
    CAMPINAS_CDP("Campinas - CDP"),
    HORTOLANDIA_CDP("Hortolândia - CDP"),
    HORTOLANDIA_CPP("Hortolândia - CPP (Penit. I)"),
    CAPELA_ALTO_PENIT_I("Capela do Alto - Penit. I + PRSA"),
    CAPELA_ALTO_PENIT_II("Capela do Alto - Penit. II \"Dr. Enio Mendes Junior\" + PRSA + PC"),
    CERQUEIRA_CESAR_PENIT_I("Cerqueira César - Penit. I + APP"),
    CERQUEIRA_CESAR_PENIT_II("Cerqueira César - Penit. II"),
    FRANCO_ROCHA_PENIT_I("Franco da Rocha - Penit. I \"Mário Moura Albuquerque\" + APP + PRSA"),
    FRANCO_ROCHA_PENIT_II("Franco da Rocha - Penit. II \"Nilton Silva\""),
    FRANCO_ROCHA_PENIT_III("Franco da Rocha - Penit. III \"José Aparecido Ribeiro\""),
    FRANCO_ROCHA_CDP("Franco da Rocha - CDP + PRSA"),
    GALIA_PENIT_I("Gália - Penit. I + PRSA + PC"),
    GALIA_PENIT_II("Gália - Penit. II + PRSA + PC"),
    GUAREI_PENIT_I("Guareí - Penit. I \"Nelson Vieira\""),
    GUAREI_PENIT_II("Guareí - Penit. II + PC"),
    GUARULHOS_PENIT_I("Guarulhos - Penit. I \"José Parada Neto\" + PRSA"),
    GUARULHOS_PENIT_II("Guarulhos - Penit. II \"Adriano Marrey\" RSA"),
    GUARULHOS_CDP_I("Guarulhos - CDP I \"ASP Giovani Martins Rodrigues\" + PRSA"),
    GUARULHOS_CDP_II("Guarulhos - CDP II + APP + PC"),
    ITAPETININGA_PENIT_I("Itapetininga - Penit. I \"Jairo de Almeida Bueno\" + APP"),
    ITAPETININGA_PENIT_II("Itapetininga - Penit. II \"ASP Maria Filomena de Sousa Dias\" + APP"),
    ITAPETININGA_CR("Itapetininga - CR - Regime: semiaberto"),
    LAVINIA_PENIT_I("Lavínia - Penit. I \"Vereador Frederico Geometti\""),
    LAVINIA_PENIT_II("Lavínia - Penit. II \"Luis Aparecido Fernandes\""),
    LAVINIA_PENIT_III("Lavínia - Penit. III \"ASP Paulo Guimarães\""),
    LAVINIA_CDP("Lavínia - CDP \"ASP Cláudio Chaves do Nascimento\" + PC"),
    MARILIA_PENIT("Marília - Penit. \"José Luiz Mansur\" + PRSA"),
    MARILIA_CR("Marília - CR - Regime: semiaberto"),
    MIRANDOPOLIS_PENIT_I("Mirandópolis - Penit. I \"Nestor Canoa\" + PRSA"),
    MIRANDOPOLIS_PENIT_II("Mirandópolis - Penit. II \"ASP Lindolfo Terçariol Filho\""),
    OSASCO_CDP_I("Osasco - CDP I \"ASP Ederson Vieira de Jesus\""),
    OSASCO_CDP_II("Osasco - CDP II \"ASP Vanda Rita Brito do Rego\""),
    PACAEMBU_PENIT("Pacaembu - Penit. \"Ozias Lúcio dos Santos\""),
    PACAEMBU_CPP("Pacaembu - CPP"),
    PACAEMBU_CDP_I("Pacaembu - CDP I + PC"),
    PACAEMBU_CDP_II("Pacaembu - CDP II"),
    PIRAJUI_PENIT_I("Pirajuí - Penit. I \"Dr. Walter Faria Pereira de Queiróz\" + PRSA"),
    PIRAJUI_PENIT_II("Pirajuí - Penit. II \"Luiz Gonzaga Vieira\""),
    POTIM_PENIT_I("Potim - Penit. I \"AEVP Jair Guimarães de Lima\" + PRSA"),
    POTIM_PENIT_II("Potim - Penit. II + APP"),
    PRESIDENTE_BERNARDES_PENIT("Presidente Bernardes - Penit. \"Silvio Yoshihiko Hinohara\" + APP"),
    PRESIDENTE_BERNARDES_CRP("Presidente Bernardes - Centro de Readaptação Penitenciária \"Dr. José Ismael Pedrosa\" (M e F)"),
    PRESIDENTE_PRUDENTE_PENIT("Presidente Prudente - Penit. \"Wellington Rodrigo Segura\" + PRSA + PC"),
    PRESIDENTE_PRUDENTE_CR("Presidente Prudente - CR \"ASP Gláucio Reinaldo Mendes Pereira\" + RSA + PC"),
    REGINOPOLIS_PENIT_I("Reginópolis - Penit. I \"Tenente PM José Alfredo Cintra Borin\" + APP + PC"),
    REGINOPOLIS_PENIT_II("Reginópolis - Penit. II \"Sgto. PM Antonio Luiz de Souza\" + PC"),
    RIBEIRAO_PRETO_PENIT("Ribeirão Preto - Penit. + APP"),
    RIBEIRAO_PRETO_CDP("Ribeirão Preto - CDP \"ASP Nayan Xavier Ribeiro\""),
    RIOLANDIA_PENIT("Riolândia - Penit. \"João Batista de Santana\""),
    RIOLANDIA_CDP("Riolândia - CDP \"ASP Valdecir Fabiano\""),
    SAO_JOSE_RIO_PRETO_CDP("São José do Rio Preto - CDP"),
    SAO_JOSE_RIO_PRETO_CPP("São José do Rio Preto - CPP \"Dr. Javert de Andrade\""),
    SAO_JOSE_RIO_PRETO_CR_FEM("São José do Rio Preto - CR Feminino + RSA + PC"),
    SAO_PAULO_CDP_BELEM_I("São Paulo - CDP I de Chácara Belém + APP"),
    SAO_PAULO_CDP_BELEM_II("São Paulo - CDP II \"ASP Paulo Gilberto de Araújo\" de Chácara Belém + APP"),
    SAO_PAULO_CDP_PINHEIROS_I("São Paulo - CDP I \"ASP Vicente Luzan da Silva\" de Pinheiros + APP"),
    SAO_PAULO_CDP_PINHEIROS_II("São Paulo - CDP II \"ASP Willians Nogueira Benjamin\" de Pinheiros"),
    SAO_PAULO_CDP_PINHEIROS_III("São Paulo - CDP III de Pinheiros + APP"),
    SAO_PAULO_CDP_PINHEIROS_IV("São Paulo - CDP IV de Pinheiros"),
    SAO_VICENTE_PENIT_I("São Vicente - Penit. I \"Dr. Geraldo de Andrade Vieira\" + APP + PC"),
    SAO_VICENTE_PENIT_II("São Vicente - Penit. II + APP"),
    SAO_VICENTE_CDP("São Vicente - CDP \"Luis Cesar Lacerda\" + APP"),
    SERRA_AZUL_PENIT_I("Serra Azul - Penit. I"),
    SERRA_AZUL_PENIT_II("Serra Azul - Penit. II + PRSA"),
    SERRA_AZUL_PENIT_III("Serra Azul - Penit. III \"ASP Sandro Alves da Silva\""),
    SOROCABA_PENIT_II("Sorocaba - Penit. II \"Dr. Antônio de Souza Neto\" + APP + PC"),
    SOROCABA_CDP("Sorocaba - CDP + APP"),
    TREMEBE_PENIT_I("Tremembé - Penit. I \"Dr. Tarcizo Leonce Pinheiro Cintra\" + APP + PC"),
    TREMEBE_PENIT_II("Tremembé - Penit. II \"Dr. José Augusto César Salgado\" RSA"),
    TREMEBE_PENIT_FEM_II("Tremembé - Penit. Feminina II + APP + PC"),
    TUPI_PAULISTA_PENIT("Tupi Paulista - Penit. \"Vanderlei Tartari Monteiro\" + PC"),
    TUPI_PAULISTA_PENIT_FEM("Tupi Paulista - Penit. Feminina + APP + PC"),
    VALPARAISO_PENIT("Valparaíso - Penit."),
    VALPARAISO_CPP("Valparaíso - CPP"),
    ANDRADINA_PENIT("Andradina - Penit. \"ASP. Anísio Aparecido de Oliveira\" + PC"),
    ARARAQUARA_PENIT("Araraquara - Penit. \"Dr. Sebastião Martins Silveira\" + PRSA + PC"),
    ASSIS_PENIT("Assis - Penit. RSA"),
    AVANHANDAVA_PENIT("Avanhandava - Penit. \"Valdic Junio Alves Primo\" + PC"),
    AVARE_PENIT_I("Avaré - Penit. I \"Dr. Paulo Luciano de Campos\""),
    AVARE_PENIT_II("Avaré - Penit. II \"Nelson Marcondes do Amaral\" + PRSA"),
    BERNARDINO_CAMPOS_PENIT("Bernardino de Campos - Penit. + APP + PC"),
    CAMPINAS_PENIT_FEM("Campinas - Penit. Feminina RSA"),
    CASA_BRANCA_PENIT("Casa Branca - Penit. \"Joaquim de Sylos Cintra\""),
    DRACENA_PENIT("Dracena - Penit. \"ASP Adriano Aparecido de Pieri\""),
    FLORIDA_PAULISTA_PENIT("Flórida Paulista - Penit. \"AEVP Cristiano Oliveira\""),
    FLORINEA_PENIT("Florínea - Penit. + PC"),
    FRANCA_PENIT("Franca - Penit. + PRSA"),
    GETULINA_PENIT("Getulina - Penit. \"Osiris Souza e Silva\" + PRSA"),
    IARAS_PENIT("Iaras - Penit. \"Orlando Brando Filinto\" + APP"),
    IPERO_PENIT("Iperó - Penit. \"Odon Ramos Maranhão\" + APP"),
    IRAPURU_PENIT("Irapuru - Penit."),
    ITAI_PENIT("Itaí - Penit. \"Cabo PM Marcelo Pires da Silva\" RSA"),
    ITATINGA_PENIT("Itatinga - Penit. + PC"),
    ITIRAPINA_PENIT_I("Itirapina - Penit. I \"Dr. Antônio de Queiróz Filho\" + PRSA + PC"),
    ITIRAPINA_PENIT_II("Itirapina - Penit. II \"João Batista de Arruda Sampaio\" + APP + PC"),
    JUNQUEIROPOLIS_PENIT("Junqueirópolis - Penit."),
    LIMEIRA_PENIT("Limeira - Penit. + PRSA + PC"),
    LUCELIA_PENIT("Lucélia - Penit. + APP + PC"),
    MAIRINQUE_PENIT("Mairinque - Penit. + PRSA"),
    MARABA_PAULISTA_PENIT("Marabá Paulista - Penit. Compacta \"João Augustinho Panucci\""),
    MARTINOPOLIS_PENIT("Martinópolis - Penit. \"Tacyan Menezes de Lucena\""),
    MOGI_GUACU_PENIT_FEM("Mogi Guaçu - Penit. Feminina + APP + PC"),
    OSVALDO_CRUZ_PENIT("Osvaldo Cruz - Penit. RSA"),
    PARAGUACU_PAULISTA_PENIT("Paraguaçu Paulista - Penit. Compacta + PC"),
    PIRACICABA_PENIT("Piracicaba - Penit. \"ASP Luís Ricardo Jock Stoduto\" + PRSA"),
    PIRAJUI_PENIT_FEM("Pirajuí - Penit. Feminina \"Sandra Aparecida Lario Vianna\" + APP + PC"),
    PONTAL_PENIT("Pontal - Penit. + PRSA + PC"),
    PRACINHA_PENIT("Pracinha - Penit. Compacta + PC"),
    PRESIDENTE_VENCESLAU_PENIT_I("Presidente Venceslau - Penit. I \"Zwinglio Ferreira\" + APP"),
    PRESIDENTE_VENCESLAU_PENIT_II("Presidente Venceslau - Penit. II \"Maurício Henrique Guimarães Pereira\""),
    REGISTRO_PENIT("Registro - Penit. + PRSA"),
    RIBEIRAO_PRETO_PENIT_FEM("Ribeirão Preto - Penit. Feminina + APP + PC"),
    SAO_PAULO_PENIT_CAPITAL("São Paulo - Penit. da Capital RSA"),
    SAO_PAULO_PENIT_FEM_SANTANA("São Paulo - Penit. Feminina Sant´Ana + PC"),
    SAO_PAULO_PENIT_PARELEIROS("São Paulo - Penit. \"ASP Joaquim Fonseca Lopes\" de Parelheiros + APP"),
    SOROCABA_PENIT_I("Sorocaba - Penit. I \"Dr. Danilo Pinheiro\" + PRSA"),
    TAIUVA_PENIT("Taiúva - Penit. RSA"),
    TAQUARITUBA_PENIT("Taquarituba - Penit. + APP"),
    TREMEBE_PENIT_FEM_I("Tremembé - Penit. Feminina I \"Santa Maria Eufrásia Pelletier\" + APP"),
    VOTORANTIM_PENIT_FEM("Votorantim - Penit. Feminina \"Oscar Garcia Machado\" + APP + PC"),
    AGUAI_CDP("Aguaí - CDP"),
    AMERICANA_CDP("Americana - CDP \"AEVP Renato Gonçalves Rodrigues\" + APP"),
    BAURU_CDP("Bauru - CDP \"ASP Francisco Carlos Caneschi\""),
    CARAGUATATUBA_CDP("Caraguatatuba - CDP \"Dr. José Eduardo Mariz de Oliveira\" + PRSA"),
    DIADEMA_CDP("Diadema - CDP + APP"),
    ICEM_CDP("Icém - CDP \"Marcos Amilton Raysaro\" + PC"),
    ITAPECERICA_SERRA_CDP("Itapecerica da Serra - CDP \"ASP Nilton Celestino\" + APP"),
    JUNDIAI_CDP("Jundiaí - CDP \"Marcos Antônio Alves Bezerra\""),
    MAUA_CDP("Mauá - CDP + APP"),
    MOGI_DAS_CRUZES_CDP("Mogi das Cruzes - CDP + APP"),
    NOVA_INDEPENDENCIA_CDP("Nova Independência - CDP + PC"),
    PAULO_FARIA_CDP("Paulo de Faria - CDP"),
    PIRACICABA_CDP("Piracicaba - CDP \"Nelson Furlan\" + APP"),
    PRAIA_GRANDE_CDP("Praia Grande - CDP \"ASP Charles Demitre Teixeira\" + APP"),
    SANTO_ANDRE_CDP("Santo André - CDP + APP"),
    SAO_BERNARDO_CDP("São Bernardo do Campo - CDP \"Dr. Calixto Antonio\" + APP"),
    SAO_JOSE_CAMPOS_CDP("São José dos Campos - CDP + APP"),
    SAO_PAULO_CDP_VILA_INDEPENDENCIA("São Paulo - CDP de Vila Independência"),
    SUZANO_CDP("Suzano - CDP + APP"),
    TAUBATE_CDP("Taubaté - CDP \"Dr. Félix Nobre de Campos\" + PC"),
    BAURU_CPP_III("Bauru - CPP III \"Prof. Noé Azevedo\""),
    CAMPINAS_CPP("Campinas - CPP \"Prof. Ataliba Nogueira\""),
    FRANCO_ROCHA_CPP("Franco da Rocha - CPP \"ASP Moises Marcos Braga\""),
    GUARIBA_CPP("Guariba - CPP + PC"),
    JARDINOPOLIS_CPP("Jardinópolis - CPP"),
    MONGAGUA_CPP("Mongaguá - CPP \"Dr. Rubens Aleixo Sendin\""),
    PORTO_FELIZ_CPP("Porto Feliz - CPP \"Dr. Walter Erwin Hoffgen\""),
    SAO_PAULO_CPP_FEM("São Paulo - CPP Feminino \"Dra. Marina Marigo Cardoso de Oliveira\" de Butantan"),
    SAO_VICENTE_CPP("São Vicente - CPP + PC"),
    TREMEBE_CPP("Tremembé - CPP \"Dr. Edgard Magalhães Noronha\""),
    ARACATUBA_CR("Araçatuba - CR + RSA"),
    ARARAQUARA_CR("Araraquara - CR + RSA"),
    ARARAQUARA_CR_FEM("Araraquara - CR Feminino + RSA"),
    ATIBAIA_CR("Atibaia - CR"),
    AVARE_CR("Avaré - CR \"Dr. Mauro de Macedo\" + RSA"),
    BIRIGUI_CR("Birigui - CR"),
    BRAGANCA_PAULISTA_CR("Bragança Paulista - CR + RSA"),
    JAU_CR("Jaú - CR \"Dr. João Eduardo Franco Perlati\" + RSA"),
    LIMEIRA_CR("Limeira - CR + RSA"),
    LINS_CR("Lins - CR \"Dr. Manoel Carlos Muniz\" + RSA"),
    MOCOCA_CR("Mococa - CR"),
    MOGI_MIRIM_CR("Mogi Mirim - CR \"Prefeito João Missaglia\" RSA"),
    OURINHOS_CR("Ourinhos - CR + RSA"),
    PIRACICABA_CR_FEM("Piracicaba - CR Feminino \"Carlos Sidnes de Souza Cantarelli\""),
    RIO_CLARO_CR_FEM("Rio Claro - CR Feminino + RSA"),
    RIO_CLARO_CR("Rio Claro - CR \"Dr Luis Gonzaga da Arruda Campos\" + RSA"),
    SUMARE_CR("Sumaré - CR RSA + PC"),
    FRANCO_ROCHA_HCTP_I("Franco da Rocha - Hospital de Custódia e Tratamento Psiquiátrico I \"Professor André Teixeira Lima\" (M e F)"),
    FRANCO_ROCHA_HCTP_II("Franco da Rocha - Hospital de Custódia e Tratamento Psiquiátrico II (M)"),
    TAUBATE_HCTP("Taubaté - Hospital de Custódia e Tratamento Psiquiátrico \"Dr. Arnaldo Amado Ferreira\" + AEP"),
    SAO_PAULO_DASH("São Paulo - Divisão de Ações de Segurança Hospitalar (M e F)");

    private String descricao;

    UnidadePrisional(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }
}
