export const REGIME_PRISIONAL_OPTIONS = [
    { value: 'FECHADO', label: 'Fechado' },
    { value: 'SEMIABERTO', label: 'Semiaberto' },
    { value: 'ABERTO', label: 'Aberto' },
    { value: 'LIVRAMENTO_CONDICIONAL', label: 'Livramento condicional' },
    { value: 'DOMICILIAR', label: 'Domiciliar' },
    { value: 'AGUARDANDO', label: 'Aguardando' },
];

export const REU_STATUS_OPTIONS = [
    { value: 'PRIMARIO', label: 'Primário' },
    { value: 'REINCIDENTE', label: 'Reincidente' },
];

export const COMO_CONHECEU_OPTIONS = [
    { value: 'ANUNCIO', label: 'Anúncio' },
    { value: 'FAMILIA_AMIGO', label: 'É família/Amigo' },
    { value: 'GOOGLE', label: 'Google' },
    { value: 'INDICACAO', label: 'Indicação' },
    { value: 'OUTROS', label: 'Outros' },
    { value: 'PARCERIA', label: 'Parceria' },
    { value: 'REDES_SOCIAIS', label: 'Redes sociais' },
    { value: 'SITE', label: 'Site' },
];

export const STATUS_EVENTO_OPTIONS = [
    { value: 'AGENDADO', label: 'Agendado' },
    { value: 'CONCLUIDO', label: 'Concluído' },
    { value: 'CANCELADO', label: 'Cancelado' },
];

export const SEXO_OPTIONS = [
    { value: 'MASCULINO', label: 'Masculino' },
    { value: 'FEMININO', label: 'Feminino' },
];

export const UNIDADE_PRISIONAL_OPTIONS = [
    { value: 'ALVARO_CARVALHO_PENIT_I', label: 'Álvaro de Carvalho - Penit. I "Valentim Alves da Silva" + APP' },
    { value: 'ALVARO_CARVALHO_PENIT_II', label: 'Álvaro de Carvalho - Penit. II' },
    { value: 'BALBINOS_PENIT_I', label: 'Balbinos - Penit. I "Rodrigo dos Santos Freitas" + APP' },
    { value: 'BALBINOS_PENIT_II', label: 'Balbinos - Penit. II "Gilmar Monteiro de Souza"' },
    { value: 'BAURU_CPP_I', label: 'Bauru - CPP I "Dr. Alberto Brocchieri"' },
    { value: 'BAURU_CPP_II', label: 'Bauru - CPP II "Dr. Eduardo de Oliveira Vianna"' },
    { value: 'CAIUA_PENIT', label: 'Caiuá - Penit. "Bruno Luiz Airoldi Leite"' },
    { value: 'CAIUA_CDP', label: 'Caiuá - CDP "Tácio Aparecido Santana" + PC' },
    { value: 'HORTOLANDIA_PENIT_II', label: 'Hortolândia - Penit. II "Odete Leite de Campos Critter" RSA' },
    { value: 'HORTOLANDIA_PENIT_III', label: 'Hortolândia - Penit. III' },
    { value: 'CAMPINAS_CDP', label: 'Campinas - CDP' },
    { value: 'HORTOLANDIA_CDP', label: 'Hortolândia - CDP' },
    { value: 'HORTOLANDIA_CPP', label: 'Hortolândia - CPP (Penit. I)' },
    { value: 'CAPELA_ALTO_PENIT_I', label: 'Capela do Alto - Penit. I + PRSA' },
    { value: 'CAPELA_ALTO_PENIT_II', label: 'Capela do Alto - Penit. II "Dr. Enio Mendes Junior" + PRSA + PC' },
    { value: 'CERQUEIRA_CESAR_PENIT_I', label: 'Cerqueira César - Penit. I + APP' },
    { value: 'CERQUEIRA_CESAR_PENIT_II', label: 'Cerqueira César - Penit. II' },
    { value: 'FRANCO_ROCHA_PENIT_I', label: 'Franco da Rocha - Penit. I "Mário Moura Albuquerque" + APP + PRSA' },
    { value: 'FRANCO_ROCHA_PENIT_II', label: 'Franco da Rocha - Penit. II "Nilton Silva"' },
    { value: 'FRANCO_ROCHA_PENIT_III', label: 'Franco da Rocha - Penit. III "José Aparecido Ribeiro"' },
    { value: 'FRANCO_ROCHA_CDP', label: 'Franco da Rocha - CDP + PRSA' },
    { value: 'GALIA_PENIT_I', label: 'Gália - Penit. I + PRSA + PC' },
    { value: 'GALIA_PENIT_II', label: 'Gália - Penit. II + PRSA + PC' },
    { value: 'GUAREI_PENIT_I', label: 'Guareí - Penit. I "Nelson Vieira"' },
    { value: 'GUAREI_PENIT_II', label: 'Guareí - Penit. II + PC' },
    { value: 'GUARULHOS_PENIT_I', label: 'Guarulhos - Penit. I "José Parada Neto" + PRSA' },
    { value: 'GUARULHOS_PENIT_II', label: 'Guarulhos - Penit. II "Adriano Marrey" RSA' },
    { value: 'GUARULHOS_CDP_I', label: 'Guarulhos - CDP I "ASP Giovani Martins Rodrigues" + PRSA' },
    { value: 'GUARULHOS_CDP_II', label: 'Guarulhos - CDP II + APP + PC' },
    { value: 'ITAPETININGA_PENIT_I', label: 'Itapetininga - Penit. I "Jairo de Almeida Bueno" + APP' },
    { value: 'ITAPETININGA_PENIT_II', label: 'Itapetininga - Penit. II "ASP Maria Filomena de Sousa Dias" + APP' },
    { value: 'ITAPETININGA_CR', label: 'Itapetininga - CR - Regime: semiaberto' },
    { value: 'LAVINIA_PENIT_I', label: 'Lavínia - Penit. I "Vereador Frederico Geometti"' },
    { value: 'LAVINIA_PENIT_II', label: 'Lavínia - Penit. II "Luis Aparecido Fernandes"' },
    { value: 'LAVINIA_PENIT_III', label: 'Lavínia - Penit. III "ASP Paulo Guimarães"' },
    { value: 'LAVINIA_CDP', label: 'Lavínia - CDP "ASP Cláudio Chaves do Nascimento" + PC' },
    { value: 'MARILIA_PENIT', label: 'Marília - Penit. "José Luiz Mansur" + PRSA' },
    { value: 'MARILIA_CR', label: 'Marília - CR - Regime: semiaberto' },
    { value: 'MIRANDOPOLIS_PENIT_I', label: 'Mirandópolis - Penit. I "Nestor Canoa" + PRSA' },
    { value: 'MIRANDOPOLIS_PENIT_II', label: 'Mirandópolis - Penit. II "ASP Lindolfo Terçariol Filho"' },
    { value: 'OSASCO_CDP_I', label: 'Osasco - CDP I "ASP Ederson Vieira de Jesus"' },
    { value: 'OSASCO_CDP_II', label: 'Osasco - CDP II "ASP Vanda Rita Brito do Rego"' },
    { value: 'PACAEMBU_PENIT', label: 'Pacaembu - Penit. "Ozias Lúcio dos Santos"' },
    { value: 'PACAEMBU_CPP', label: 'Pacaembu - CPP' },
    { value: 'PACAEMBU_CDP_I', label: 'Pacaembu - CDP I + PC' },
    { value: 'PACAEMBU_CDP_II', label: 'Pacaembu - CDP II' },
    { value: 'PIRAJUI_PENIT_I', label: 'Pirajuí - Penit. I "Dr. Walter Faria Pereira de Queiróz" + PRSA' },
    { value: 'PIRAJUI_PENIT_II', label: 'Pirajuí - Penit. II "Luiz Gonzaga Vieira"' },
    { value: 'POTIM_PENIT_I', label: 'Potim - Penit. I "AEVP Jair Guimarães de Lima" + PRSA' },
    { value: 'POTIM_PENIT_II', label: 'Potim - Penit. II + APP' },
    { value: 'PRESIDENTE_BERNARDES_PENIT', label: 'Presidente Bernardes - Penit. "Silvio Yoshihiko Hinohara" + APP' },
    { value: 'PRESIDENTE_BERNARDES_CRP', label: 'Presidente Bernardes - Centro de Readaptação Penitenciária "Dr. José Ismael Pedrosa" (M e F)' },
    { value: 'PRESIDENTE_PRUDENTE_PENIT', label: 'Presidente Prudente - Penit. "Wellington Rodrigo Segura" + PRSA + PC' },
    { value: 'PRESIDENTE_PRUDENTE_CR', label: 'Presidente Prudente - CR "ASP Gláucio Reinaldo Mendes Pereira" + RSA + PC' },
    { value: 'REGINOPOLIS_PENIT_I', label: 'Reginópolis - Penit. I "Tenente PM José Alfredo Cintra Borin" + APP + PC' },
    { value: 'REGINOPOLIS_PENIT_II', label: 'Reginópolis - Penit. II "Sgto. PM Antonio Luiz de Souza" + PC' },
    { value: 'RIBEIRAO_PRETO_PENIT', label: 'Ribeirão Preto - Penit. + APP' },
    { value: 'RIBEIRAO_PRETO_CDP', label: 'Ribeirão Preto - CDP "ASP Nayan Xavier Ribeiro"' },
    { value: 'RIOLANDIA_PENIT', label: 'Riolândia - Penit. "João Batista de Santana"' },
    { value: 'RIOLANDIA_CDP', label: 'Riolândia - CDP "ASP Valdecir Fabiano"' },
    { value: 'SAO_JOSE_RIO_PRETO_CDP', label: 'São José do Rio Preto - CDP' },
    { value: 'SAO_JOSE_RIO_PRETO_CPP', label: 'São José do Rio Preto - CPP "Dr. Javert de Andrade"' },
    { value: 'SAO_JOSE_RIO_PRETO_CR_FEM', label: 'São José do Rio Preto - CR Feminino + RSA + PC' },
    { value: 'SAO_PAULO_CDP_BELEM_I', label: 'São Paulo - CDP I de Chácara Belém + APP' },
    { value: 'SAO_PAULO_CDP_BELEM_II', label: 'São Paulo - CDP II "ASP Paulo Gilberto de Araújo" de Chácara Belém + APP' },
    { value: 'SAO_PAULO_CDP_PINHEIROS_I', label: 'São Paulo - CDP I "ASP Vicente Luzan da Silva" de Pinheiros + APP' },
    { value: 'SAO_PAULO_CDP_PINHEIROS_II', label: 'São Paulo - CDP II "ASP Willians Nogueira Benjamin" de Pinheiros' },
    { value: 'SAO_PAULO_CDP_PINHEIROS_III', label: 'São Paulo - CDP III de Pinheiros + APP' },
    { value: 'SAO_PAULO_CDP_PINHEIROS_IV', label: 'São Paulo - CDP IV de Pinheiros' },
    { value: 'SAO_VICENTE_PENIT_I', label: 'São Vicente - Penit. I "Dr. Geraldo de Andrade Vieira" + APP + PC' },
    { value: 'SAO_VICENTE_PENIT_II', label: 'São Vicente - Penit. II + APP' },
    { value: 'SAO_VICENTE_CDP', label: 'São Vicente - CDP "Luis Cesar Lacerda" + APP' },
    { value: 'SERRA_AZUL_PENIT_I', label: 'Serra Azul - Penit. I' },
    { value: 'SERRA_AZUL_PENIT_II', label: 'Serra Azul - Penit. II + PRSA' },
    { value: 'SERRA_AZUL_PENIT_III', label: 'Serra Azul - Penit. III "ASP Sandro Alves da Silva"' },
    { value: 'SOROCABA_PENIT_II', label: 'Sorocaba - Penit. II "Dr. Antônio de Souza Neto" + APP + PC' },
    { value: 'SOROCABA_CDP', label: 'Sorocaba - CDP + APP' },
    { value: 'TREMEBE_PENIT_I', label: 'Tremembé - Penit. I "Dr. Tarcizo Leonce Pinheiro Cintra" + APP + PC' },
    { value: 'TREMEBE_PENIT_II', label: 'Tremembé - Penit. II "Dr. José Augusto César Salgado" RSA' },
    { value: 'TREMEBE_PENIT_FEM_II', label: 'Tremembé - Penit. Feminina II + APP + PC' },
    { value: 'TUPI_PAULISTA_PENIT', label: 'Tupi Paulista - Penit. "Vanderlei Tartari Monteiro" + PC' },
    { value: 'TUPI_PAULISTA_PENIT_FEM', label: 'Tupi Paulista - Penit. Feminina + APP + PC' },
    { value: 'VALPARAISO_PENIT', label: 'Valparaíso - Penit.' },
    { value: 'VALPARAISO_CPP', label: 'Valparaíso - CPP' },
    { value: 'ANDRADINA_PENIT', label: 'Andradina - Penit. "ASP. Anísio Aparecido de Oliveira" + PC' },
    { value: 'ARARAQUARA_PENIT', label: 'Araraquara - Penit. "Dr. Sebastião Martins Silveira" + PRSA + PC' },
    { value: 'ASSIS_PENIT', label: 'Assis - Penit. RSA' },
    { value: 'AVANHANDAVA_PENIT', label: 'Avanhandava - Penit. "Valdic Junio Alves Primo" + PC' },
    { value: 'AVARE_PENIT_I', label: 'Avaré - Penit. I "Dr. Paulo Luciano de Campos"' },
    { value: 'AVARE_PENIT_II', label: 'Avaré - Penit. II "Nelson Marcondes do Amaral" + PRSA' },
    { value: 'BERNARDINO_CAMPOS_PENIT', label: 'Bernardino de Campos - Penit. + APP + PC' },
    { value: 'CAMPINAS_PENIT_FEM', label: 'Campinas - Penit. Feminina RSA' },
    { value: 'CASA_BRANCA_PENIT', label: 'Casa Branca - Penit. "Joaquim de Sylos Cintra"' },
    { value: 'DRACENA_PENIT', label: 'Dracena - Penit. "ASP Adriano Aparecido de Pieri"' },
    { value: 'FLORIDA_PAULISTA_PENIT', label: 'Flórida Paulista - Penit. "AEVP Cristiano Oliveira"' },
    { value: 'FLORINEA_PENIT', label: 'Florínea - Penit. + PC' },
    { value: 'FRANCA_PENIT', label: 'Franca - Penit. + PRSA' },
    { value: 'GETULINA_PENIT', label: 'Getulina - Penit. "Osiris Souza e Silva" + PRSA' },
    { value: 'IARAS_PENIT', label: 'Iaras - Penit. "Orlando Brando Filinto" + APP' },
    { value: 'IPERO_PENIT', label: 'Iperó - Penit. "Odon Ramos Maranhão" + APP' },
    { value: 'IRAPURU_PENIT', label: 'Irapuru - Penit.' },
    { value: 'ITAI_PENIT', label: 'Itaí - Penit. "Cabo PM Marcelo Pires da Silva" RSA' },
    { value: 'ITATINGA_PENIT', label: 'Itatinga - Penit. + PC' },
    { value: 'ITIRAPINA_PENIT_I', label: 'Itirapina - Penit. I "Dr. Antônio de Queiróz Filho" + PRSA + PC' },
    { value: 'ITIRAPINA_PENIT_II', label: 'Itirapina - Penit. II "João Batista de Arruda Sampaio" + APP + PC' },
    { value: 'JUNQUEIROPOLIS_PENIT', label: 'Junqueirópolis - Penit.' },
    { value: 'LIMEIRA_PENIT', label: 'Limeira - Penit. + PRSA + PC' },
    { value: 'LUCELIA_PENIT', label: 'Lucélia - Penit. + APP + PC' },
    { value: 'MAIRINQUE_PENIT', label: 'Mairinque - Penit. + PRSA' },
    { value: 'MARABA_PAULISTA_PENIT', label: 'Marabá Paulista - Penit. Compacta "João Augustinho Panucci"' },
    { value: 'MARTINOPOLIS_PENIT', label: 'Martinópolis - Penit. "Tacyan Menezes de Lucena"' },
    { value: 'MOGI_GUACU_PENIT_FEM', label: 'Mogi Guaçu - Penit. Feminina + APP + PC' },
    { value: 'OSVALDO_CRUZ_PENIT', label: 'Osvaldo Cruz - Penit. RSA' },
    { value: 'PARAGUACU_PAULISTA_PENIT', label: 'Paraguaçu Paulista - Penit. Compacta + PC' },
    { value: 'PIRACICABA_PENIT', label: 'Piracicaba - Penit. "ASP Luís Ricardo Jock Stoduto" + PRSA' },
    { value: 'PIRAJUI_PENIT_FEM', label: 'Pirajuí - Penit. Feminina "Sandra Aparecida Lario Vianna" + APP + PC' },
    { value: 'PONTAL_PENIT', label: 'Pontal - Penit. + PRSA + PC' },
    { value: 'PRACINHA_PENIT', label: 'Pracinha - Penit. Compacta + PC' },
    { value: 'PRESIDENTE_VENCESLAU_PENIT_I', label: 'Presidente Venceslau - Penit. I "Zwinglio Ferreira" + APP' },
    { value: 'PRESIDENTE_VENCESLAU_PENIT_II', label: 'Presidente Venceslau - Penit. II "Maurício Henrique Guimarães Pereira"' },
    { value: 'REGISTRO_PENIT', label: 'Registro - Penit. + PRSA' },
    { value: 'RIBEIRAO_PRETO_PENIT_FEM', label: 'Ribeirão Preto - Penit. Feminina + APP + PC' },
    { value: 'SAO_PAULO_PENIT_CAPITAL', label: 'São Paulo - Penit. da Capital RSA' },
    { value: 'SAO_PAULO_PENIT_FEM_SANTANA', label: 'São Paulo - Penit. Feminina Sant´Ana + PC' },
    { value: 'SAO_PAULO_PENIT_PARELEIROS', label: 'São Paulo - Penit. "ASP Joaquim Fonseca Lopes" de Parelheiros + APP' },
    { value: 'SOROCABA_PENIT_I', label: 'Sorocaba - Penit. I "Dr. Danilo Pinheiro" + PRSA' },
    { value: 'TAIUVA_PENIT', label: 'Taiúva - Penit. RSA' },
    { value: 'TAQUARITUBA_PENIT', label: 'Taquarituba - Penit. + APP' },
    { value: 'TREMEBE_PENIT_FEM_I', label: 'Tremembé - Penit. Feminina I "Santa Maria Eufrásia Pelletier" + APP' },
    { value: 'VOTORANTIM_PENIT_FEM', label: 'Votorantim - Penit. Feminina "Oscar Garcia Machado" + APP + PC' },
    { value: 'AGUAI_CDP', label: 'Aguaí - CDP' },
    { value: 'AMERICANA_CDP', label: 'Americana - CDP "AEVP Renato Gonçalves Rodrigues" + APP' },
    { value: 'BAURU_CDP', label: 'Bauru - CDP "ASP Francisco Carlos Caneschi"' },
    { value: 'CARAGUATATUBA_CDP', label: 'Caraguatatuba - CDP "Dr. José Eduardo Mariz de Oliveira" + PRSA' },
    { value: 'DIADEMA_CDP', label: 'Diadema - CDP + APP' },
    { value: 'ICEM_CDP', label: 'Icém - CDP "Marcos Amilton Raysaro" + PC' },
    { value: 'ITAPECERICA_SERRA_CDP', label: 'Itapecerica da Serra - CDP "ASP Nilton Celestino" + APP' },
    { value: 'JUNDIAI_CDP', label: 'Jundiaí - CDP "Marcos Antônio Alves Bezerra"' },
    { value: 'MAUA_CDP', label: 'Mauá - CDP + APP' },
    { value: 'MOGI_DAS_CRUZES_CDP', label: 'Mogi das Cruzes - CDP + APP' },
    { value: 'NOVA_INDEPENDENCIA_CDP', label: 'Nova Independência - CDP + PC' },
    { value: 'PAULO_FARIA_CDP', label: 'Paulo de Faria - CDP' },
    { value: 'PIRACICABA_CDP', label: 'Piracicaba - CDP "Nelson Furlan" + APP' },
    { value: 'PRAIA_GRANDE_CDP', label: 'Praia Grande - CDP "ASP Charles Demitre Teixeira" + APP' },
    { value: 'SANTO_ANDRE_CDP', label: 'Santo André - CDP + APP' },
    { value: 'SAO_BERNARDO_CDP', label: 'São Bernardo do Campo - CDP "Dr. Calixto Antonio" + APP' },
    { value: 'SAO_JOSE_CAMPOS_CDP', label: 'São José dos Campos - CDP + APP' },
    { value: 'SAO_PAULO_CDP_VILA_INDEPENDENCIA', label: 'São Paulo - CDP de Vila Independência' },
    { value: 'SUZANO_CDP', label: 'Suzano - CDP + APP' },
    { value: 'TAUBATE_CDP', label: 'Taubaté - CDP "Dr. Félix Nobre de Campos" + PC' },
    { value: 'BAURU_CPP_III', label: 'Bauru - CPP III "Prof. Noé Azevedo"' },
    { value: 'CAMPINAS_CPP', label: 'Campinas - CPP "Prof. Ataliba Nogueira"' },
    { value: 'FRANCO_ROCHA_CPP', label: 'Franco da Rocha - CPP "ASP Moises Marcos Braga"' },
    { value: 'GUARIBA_CPP', label: 'Guariba - CPP + PC' },
    { value: 'JARDINOPOLIS_CPP', label: 'Jardinópolis - CPP' },
    { value: 'MONGAGUA_CPP', label: 'Mongaguá - CPP "Dr. Rubens Aleixo Sendin"' },
    { value: 'PORTO_FELIZ_CPP', label: 'Porto Feliz - CPP "Dr. Walter Erwin Hoffgen"' },
    { value: 'SAO_PAULO_CPP_FEM', label: 'São Paulo - CPP Feminino "Dra. Marina Marigo Cardoso de Oliveira" de Butantan' },
    { value: 'SAO_VICENTE_CPP', label: 'São Vicente - CPP + PC' },
    { value: 'TREMEBE_CPP', label: 'Tremembé - CPP "Dr. Edgard Magalhães Noronha"' },
    { value: 'ARACATUBA_CR', label: 'Araçatuba - CR + RSA' },
    { value: 'ARARAQUARA_CR', label: 'Araraquara - CR + RSA' },
    { value: 'ARARAQUARA_CR_FEM', label: 'Araraquara - CR Feminino + RSA' },
    { value: 'ATIBAIA_CR', label: 'Atibaia - CR' },
    { value: 'AVARE_CR', label: 'Avaré - CR "Dr. Mauro de Macedo" + RSA' },
    { value: 'BIRIGUI_CR', label: 'Birigui - CR' },
    { value: 'BRAGANCA_PAULISTA_CR', label: 'Bragança Paulista - CR + RSA' },
    { value: 'JAU_CR', label: 'Jaú - CR "Dr. João Eduardo Franco Perlati" + RSA' },
    { value: 'LIMEIRA_CR', label: 'Limeira - CR + RSA' },
    { value: 'LINS_CR', label: 'Lins - CR "Dr. Manoel Carlos Muniz" + RSA' },
    { value: 'MOCOCA_CR', label: 'Mococa - CR' },
    { value: 'MOGI_MIRIM_CR', label: 'Mogi Mirim - CR "Prefeito João Missaglia" RSA' },
    { value: 'OURINHOS_CR', label: 'Ourinhos - CR + RSA' },
    { value: 'PIRACICABA_CR_FEM', label: 'Piracicaba - CR Feminino "Carlos Sidnes de Souza Cantarelli"' },
    { value: 'RIO_CLARO_CR_FEM', label: 'Rio Claro - CR Feminino + RSA' },
    { value: 'RIO_CLARO_CR', label: 'Rio Claro - CR "Dr Luis Gonzaga da Arruda Campos" + RSA' },
    { value: 'SUMARE_CR', label: 'Sumaré - CR RSA + PC' },
    { value: 'PRESIDENTE_BERNARDES_CRP', label: 'Presidente Bernardes - Centro de Readaptação Penitenciária "Dr. José Ismael Pedrosa" (M e F)' },
    { value: 'FRANCO_ROCHA_HCTP_I', label: 'Franco da Rocha - Hospital de Custódia e Tratamento Psiquiátrico I "Professor André Teixeira Lima" (M e F)' },
    { value: 'FRANCO_ROCHA_HCTP_II', label: 'Franco da Rocha - Hospital de Custódia e Tratamento Psiquiátrico II (M)' },
    { value: 'TAUBATE_HCTP', label: 'Taubaté - Hospital de Custódia e Tratamento Psiquiátrico "Dr. Arnaldo Amado Ferreira" + AEP' },
    { value: 'SAO_PAULO_DASH', label: 'São Paulo - Divisão de Ações de Segurança Hospitalar (M e F)' },
];

export const SIM_NAO_OPTIONS = [
    { value: 'SIM', label: 'Sim' },
    { value: 'NAO', label: 'Não' },
];

export const STATUS_PROVIDENCIA_OPTIONS = [
    { value: 'PENDENTE', label: 'Pendente' },
    { value: 'EM_ANDAMENTO', label: 'Em andamento' },
    { value: 'CONCLUIDA', label: 'Concluída' },
];

export const TIPO_PROVIDENCIA_OPTIONS = [
    { value: 'HABILITACAO_REVOGACAO', label: 'Habilitação/Revogação' },
    { value: 'ATESTADOS_TRABALHO', label: 'Atestados de Trabalho' },
    { value: 'ATESTADOS_ESTUDOS', label: 'Atestados de Estudos' },
    { value: 'CURSOS', label: 'Cursos' },
    { value: 'ENCCEJA', label: 'ENCCEJA' },
    { value: 'ENEM', label: 'ENEM' },
    { value: 'LEITURA', label: 'Leitura' },
    { value: 'DETRACAO', label: 'Detração' },
    { value: 'COMUTACAO', label: 'Comutação' },
    { value: 'INDULTO', label: 'Indulto' },
    { value: 'APROXIMACAO_FAMILIAR', label: 'Aproximação familiar' },
];

export const STATUS_TAREFA_OPTIONS = [
    { value: 'NAO_INICIADA', label: 'Não iniciada' },
    { value: 'EM_ANDAMENTO', label: 'Em andamento' },
    { value: 'CONCLUIDA', label: 'Concluída' },
];

export const URGENCIA_TAREFA_OPTIONS = [
    { value: 'EXIGE_ATENCAO_IMEDIATA', label: 'Exige atenção imediata' },
    { value: 'MUITO_URGENTE', label: 'Muito urgente' },
    { value: 'REQUER_ATENCAO', label: 'Requer atenção' },
    { value: 'POUCO_URGENTE', label: 'Pouco urgente' },
];